export type StockAnalysisMessage = {
  item_id: string;
  role: string;
  event?: string | null;
  conversation_id?: string | null;
  content: string;
  answer_basis: string;
  mode: string;
  used_context_ids: number[];
  missing_context_hints: string[];
  compared_tickers: string[];
  comparison_mode: boolean;
  stale_context_ids: number[];
  refresh_recommended_context_ids: number[];
  tool_reason?: string | null;
  tool_calls_summary: string[];
  temporary_evidence_blocks: {
    evidence_id?: string;
    type: string;
    title: string;
    summary: string;
    temporary: boolean;
    source_module?: string;
    source_label?: string;
    is_external?: boolean;
    generated_at?: string | null;
    data_time?: string | null;
    staleness_hint?: string | null;
    ticker_refs_json?: string[];
    theme_refs_json?: string[];
    payload?: Record<string, unknown>;
  }[];
  unavailable_tools: {
    tool: string;
    reason: string;
    ticker?: string;
  }[];
  used_internal_sources: string[];
  used_external_sources: string[];
  provider_attempts: Array<Record<string, unknown>>;
  provider_used: string[];
  provider_fallback_chain: string[];
  evidence_generated_at?: string | null;
  evidence_staleness_hint?: string | null;
  refreshed_before_answer: boolean;
  refresh_run_summary?: string | null;
  refreshed_context_ids: number[];
  refresh_failed_context_ids: number[];
  refresh_skipped_context_ids: number[];
  refresh_changed_contexts: Array<Record<string, unknown>>;
  used_active_memory: boolean;
  active_memory_id?: number | null;
  active_memory_title?: string | null;
  active_memory_updated_at?: string | null;
  active_memory_version?: number | null;
  used_active_compression: boolean;
  active_compression_id?: number | null;
  active_compression_title?: string | null;
  active_compression_updated_at?: string | null;
  active_compression_version?: number | null;
  active_compression_covered_until_message_id?: string | null;
  active_compression_covered_message_count?: number | null;
  recent_raw_message_count: number;
  compression_recommended: boolean;
  compression_reason?: string | null;
  uncompressed_message_count: number;
  estimated_history_size: number;
  active_compression_stale: boolean;
  question_intent?: string | null;
  response_strategy?: string | null;
  routing_reason?: string | null;
  recommended_next_action?: string | null;
  followup_candidates: string[];
  suggested_task_titles: string[];
  execution_plan_summary?: string | null;
  executed_steps: Array<Record<string, unknown>>;
  skipped_steps: Array<Record<string, unknown>>;
  failed_steps: Array<Record<string, unknown>>;
  related_task_ids: number[];
  task_update_suggestions: Array<Record<string, unknown>>;
  validation_summary: Record<string, unknown>;
  thesis_change_hint?: string | null;
  focus_tickers: string[];
  focus_themes: string[];
};

export type StockAnalysisMessageList = {
  conversation_id: string;
  thread_id: number;
  items: StockAnalysisMessage[];
  count: number;
};

export type StockAnalysisMessageCreateResult = {
  conversation_id: string;
  thread_id: number;
  answer_basis: string;
  mode: string;
  used_context_ids: number[];
  missing_context_hints: string[];
  compared_tickers: string[];
  comparison_mode: boolean;
  stale_context_ids: number[];
  refresh_recommended_context_ids: number[];
  tool_reason?: string | null;
  tool_calls_summary: string[];
  temporary_evidence_blocks: {
    evidence_id?: string;
    type: string;
    title: string;
    summary: string;
    temporary: boolean;
    source_module?: string;
    source_label?: string;
    is_external?: boolean;
    generated_at?: string | null;
    data_time?: string | null;
    staleness_hint?: string | null;
    ticker_refs_json?: string[];
    theme_refs_json?: string[];
    payload?: Record<string, unknown>;
  }[];
  unavailable_tools: {
    tool: string;
    reason: string;
    ticker?: string;
  }[];
  used_internal_sources: string[];
  used_external_sources: string[];
  provider_attempts: Array<Record<string, unknown>>;
  provider_used: string[];
  provider_fallback_chain: string[];
  evidence_generated_at?: string | null;
  evidence_staleness_hint?: string | null;
  refreshed_before_answer: boolean;
  refresh_run_summary?: string | null;
  refreshed_context_ids: number[];
  refresh_failed_context_ids: number[];
  refresh_skipped_context_ids: number[];
  refresh_changed_contexts: Array<Record<string, unknown>>;
  used_active_memory: boolean;
  active_memory_id?: number | null;
  active_memory_title?: string | null;
  active_memory_updated_at?: string | null;
  active_memory_version?: number | null;
  used_active_compression: boolean;
  active_compression_id?: number | null;
  active_compression_title?: string | null;
  active_compression_updated_at?: string | null;
  active_compression_version?: number | null;
  active_compression_covered_until_message_id?: string | null;
  active_compression_covered_message_count?: number | null;
  recent_raw_message_count: number;
  compression_recommended: boolean;
  compression_reason?: string | null;
  uncompressed_message_count: number;
  estimated_history_size: number;
  active_compression_stale: boolean;
  question_intent?: string | null;
  response_strategy?: string | null;
  routing_reason?: string | null;
  recommended_next_action?: string | null;
  followup_candidates: string[];
  suggested_task_titles: string[];
  execution_plan_summary?: string | null;
  executed_steps: Array<Record<string, unknown>>;
  skipped_steps: Array<Record<string, unknown>>;
  failed_steps: Array<Record<string, unknown>>;
  related_task_ids: number[];
  task_update_suggestions: Array<Record<string, unknown>>;
  validation_summary: Record<string, unknown>;
  thesis_change_hint?: string | null;
  focus_tickers: string[];
  focus_themes: string[];
  user_message: StockAnalysisMessage;
  assistant_message: StockAnalysisMessage;
};

export type StockAnalysisEvidenceSaveResult = {
  thread_id: number;
  message_id: string;
  evidence_index: number;
  context_card: import("./analysis-context-card").AnalysisContextCard;
};
